### ISSUE TITLE
Search Input

### ISSUE THREAD

**Issue by Szkalownik** [antaresproject/antares-front-end#1]
Hi,

I think this search input 
![ss 2017-02-15 at 01 40 36](https://cloud.githubusercontent.com/assets/25772035/22974831/7a180986-f384-11e6-97e4-97f3e0d47579.png)

Is a low visability lvl .
Also selected background just entered text is almost the same as #02a8f3 and I must rly effort sight, to see how many letters I just selected :)

**Comment by placidlyUnsalted** [comment]
@Szkalownik 

Selection color has been fixed:
![antares-selected-text](https://cloud.githubusercontent.com/assets/3351063/23837051/375df67a-0782-11e7-9be1-95149545fcde.jpg)
