### ISSUE TITLE
[Branding] Wrong brand color after changing

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#100]
1. Go to admin/branding/area/1
2. Change Brand Color and Submit

Results:
Brand colors back to default despite the changes.

https://image.prntscr.com/image/qyzp93YwT6qlfVNFsVlwIw.png

**Comment by placidlyUnsalted** [comment]
@dawid-g - the issue has been dealt with.

**Comment by dawid-g** [comment]
verified as fixed.
