### ISSUE TITLE
Incorrect users list display on Firefox 

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#101]
Preconditions:
- Firefox 56 

1. Go to admin/users/index 

Results:
https://image.prntscr.com/image/_jzNTk6mQHmXgm0hlg6sdg.png

**Comment by dawid-g** [comment]
Issue occure on all lists, e.g  admin/sample_module/index#

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been burned on a stake. Fixed!

**Comment by dawid-g** [comment]
Ok, I will take the ash out!
