### ISSUE TITLE
[Firefox] Paranormal activity

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#102]
Firefox 56

1. Go to: admin/customfields#
2. Click Custom Fields -> Add Custom Fields

Results:

![paranormal](https://user-images.githubusercontent.com/26220123/33380325-fb3fa780-d51a-11e7-90cc-d3272db58124.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g Problem was, our browser specific hooks fired a bit too late. I've rearranged JS order in webpack bundle - no you shouldn't be able to reproduce this. Thank's for testing!

**Comment by dawid-g** [comment]
verified as fixed, bro!
