### ISSUE TITLE
Translations - Id column cases

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#105]
First: https://image.prntscr.com/image/oJCzQiFBR_WPP_xX9J4Gsg.png - should be aligned
Second: There is lack of sorting for this column

**Comment by placidlyUnsalted** [comment]
@dawid-g Can you kindly reverify the issue?

**Comment by dawid-g** [comment]
There is no possibility to sorting by ID still.

**Comment by placidlyUnsalted** [comment]
@dawid-g Sorting added.

**Comment by dawid-g** [comment]
Verified as fixed.
