### ISSUE TITLE
[Edge] Incorrect Widgets moving

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#106]
Microsoft Edge 38.14
Occure on IE 11 too.

There is very hard to disconnect mouse pointer with widget.

![wiget](https://user-images.githubusercontent.com/26220123/33480362-e92a6b12-d690-11e7-8bea-32ea7599f2b7.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g Thanks for testing, Issue fixed. :)
