### ISSUE TITLE
"Filters" - Sliders don't change the values

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#25]
Steps:

1. Go to 'Client List'
2. Click "Filter" -> "Income", and try to change values by Slider

Actual Results:

Sliders don't change the values. Gif in attachment:

![sliders](https://user-images.githubusercontent.com/26220123/27226694-8752809c-52a0-11e7-84d6-1e172a5d1aa1.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g This issue has been fixed in latest release.
