### ISSUE TITLE
Dashboard icon is highlighted regardless of the open section

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#30]
Steps:

1. Go to e.g. client list
2. Look at "Dashboard" icon on menu bar

Actual Results:

Dashboard icon is highlighted regardless of the open section    

https://puu.sh/wjIoF/c7e9ffa1e3.jpg

**Comment by placidlyUnsalted** [comment]
@dawid-g Fixed in the latest release.
