### ISSUE TITLE
Forms Vertical -> Date Range picker - there is no possibility to select date range

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#32]
Steps:

1. Go to Forms Vertical - Dev Area
2. Try to select data range in Date Range picker field

Results:

There is no possibility to select date range

**Comment by placidlyUnsalted** [comment]
@dawid-g Can't replicate the issue, selecting the date range seem to work fine on my end. Could you contribute a bit more to the problem description?
