### ISSUE TITLE
Widget Edit Toggle bar is not displayed anywhere, except dashboard

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#34]
Steps:

1. Go to e.g. to "Client list" or "ACL"
2. Click 'Widget Edit Toggle' button

Results:

https://puu.sh/wlEyv/ef5eb1f5fa.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been fixed - now the 'widget edit toggle' button in displayed only on relevant parts of the system.
