### ISSUE TITLE
Login page - logo needs improvement

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#35]
On the login page, logo currently looks like this:  https://puu.sh/wlI1g/7a1b086a3d.png

There should looks like:  https://puu.sh/wlHPU/e5b3d9b394.png 

or it should be alligned imho.

**Comment by placidlyUnsalted** [comment]
@dawid-g Thanks for your tests Dawid, logo image & styles have been corrected in the latest release.
