### ISSUE TITLE
Forms Horizontal - Dev Area - no possibility to click checkboxes

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#37]
There is no possibility to select checkboxes in "Checkbox & Radio Disabled" and "Checkbox & Radio Read-Only" sections.

**Comment by placidlyUnsalted** [comment]
@dawid-g It works like that on purpose. Those sections demonstrate these checkboxes in states that don't allow them to be interacted with. Hence the names - "disabled" and "read-only".
