### ISSUE TITLE
'Dashboard' dropdown on 'Error 400' page

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#40]
Imho there shouldn't be displayed 'Dashboard' dropdown on 'Error 400' page.

https://puu.sh/wlNcT/eb7367b5aa.jpg

**Comment by placidlyUnsalted** [comment]
@dawid-g You're right - breadcrumbs are no longer visible on the system error pages. https://puu.sh/wC5Nn/2b99f3938a.png
