### ISSUE TITLE
Unselecting the selected records is unhandy

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#42]
Steps:

1. Go to random list e.g. client list
2. Select all record 
3. Try to unselect, by mouse clicking

Actual Results:

Unselecting the selected records is unhandy. Look at gif below:

![unh](https://user-images.githubusercontent.com/26220123/27272955-2aba3666-54cd-11e7-941c-db76588f4458.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g We're planning big improvements to tables & selecting mechanics in next release ( 0.9.4 ).
