### ISSUE TITLE
Resolution 1366x768 - invalid sections alignment

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#45]
"Client details" section:

- [x] 1. https://puu.sh/wof8n/dcf980663a.jpg

- [x] 2. https://puu.sh/wofoU/eefc3045c7.jpg

"Email Settings" section:

- [x] 1. https://puu.sh/wolg6/56245a1c46.jpg

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been fixed.
