### ISSUE TITLE
[Mobile] Lack of actions buttons on lists

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#47]
Precondeitions:
device: Galaxy S4 - 360 x 640

1. Go to e.g. client list
2. Expand the options for random customer by arrow

Results:
Lack of actions button - https://puu.sh/wplBt/402a6da124.png

**Comment by placidlyUnsalted** [comment]
@dawid-g In the current release, _context menu_ works by pressing (>300ms) table row. In future, we're planning on adding a special button for the context menu, once we'll figure out how to do "rows selecting" on mobile devices.
