### ISSUE TITLE
[Mobile] Client Details - Lack of one subsection

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#48]
Preconditions:
device: Galaxy S4 - 360 x 640

1. Go to 'Client Details'

Results:

desktop: https://puu.sh/wplW0/106c6b9485.png
mobile: https://puu.sh/wplYV/0f2b5c12e3.png   - lack of "Tickets"

**Comment by placidlyUnsalted** [comment]
@dawid-g That issue has been fixed - now, sections are scrolling horizontally on mobile: https://i.imgur.com/QALwRI8.gif.
