### ISSUE TITLE
[Mobile] Lists - lack of 'Filters' and 'With Selected' buttons

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#51]
Preconditions:
device: Galaxy S4 - 360 x 640

1. Go to e.g. "Client list"

Results:

There is lack of 'Filters' and 'With Selected' buttons

**Comment by placidlyUnsalted** [comment]
@dawid-g These buttons are currently placed inside another dropdown on mobile view - in order to preserve vertical space. Check out the screenshot for details. https://puu.sh/wC5SQ/b14fc2a3bf.png
