### ISSUE TITLE
[Mobile] Widget Tabs - Merging widget instead of switching position

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#53]
Preconditions:
device: Galaxy S4 - 360 x 640

1. Go to Dashboard or e.g Widget Tabs
2. Try to switch position between two widgets

Results:

Widgets are merged instead of switching position

**Comment by placidlyUnsalted** [comment]
@dawid-g, widget position changing and merging capabilities should not be available on mobile. Issue fixed.
