### ISSUE TITLE
Notification Template - lack of flags in language fields

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#55]
Go to: /admin/notifications/create

https://image.prntscr.com/image/x0unOrVIRUSMvtpP6cPd0Q.png - flags are not displayed with the language name

**Comment by placidlyUnsalted** [comment]
@mountstone We need to fix the correct absolute path fo flag images directory.

**Comment by dawid-g** [comment]
It's ok now, closed.
