### ISSUE TITLE
Short Top Menu brand - Lack of the pull-down menu button

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#57]
1. Go to /admin/branding/area/1
2. Change brand template for admin to Short Top Menu
3. Click Submit

Actual Results:

Lack of the pull-down menu button - https://image.prntscr.com/image/UHXh-KPKTD29bXOizAuI0Q.png  

Expected Results:

Pull-down menu button with Dashboard, Users, and Sample Module sections (like in Top Menu View): 

https://image.prntscr.com/image/vz_sIQppQeCEYkl0bKx5YQ.png

**Comment by mountstone** [comment]
Fixed
