### ISSUE TITLE
[ShortTopMenu] Incorrect display of Users Online widget 

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#58]
1. Change Brand template to Short Top Menu
2. Go to Dashboard

Results:

Incorrect display of Users Online widget:  https://image.prntscr.com/image/_qbOIsESSgy71JmJebx_8g.png

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
confirmed.
