### ISSUE TITLE
[Tablet] Unnecessary redirection when attempting to unfold the menu

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#60]
Preconditions:
- Ipad Teblet view

There is redirection when attempting to unfold one of menu section. No possibility to click one of subsection.

![redirect](https://user-images.githubusercontent.com/26220123/32896432-49541592-cae3-11e7-9fe6-65c9f57dac8c.gif)

**Comment by dawid-g** [comment]
It's better, but now we have very long loading process:


![dlugo](https://user-images.githubusercontent.com/26220123/32944848-4936805a-cb91-11e7-90af-b45660ff1afc.gif)

**Comment by dawid-g** [comment]
It's better, but now we have very long loading process:


![very](https://user-images.githubusercontent.com/26220123/32944929-ae3644f4-cb91-11e7-8260-a99427500721.gif)

**Comment by dawid-g** [comment]
It's better, but now we have very long loading process:


![okoko](https://user-images.githubusercontent.com/26220123/32945089-61c5fe74-cb92-11e7-92f3-79899f020b42.gif)

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
confirmed.

**Comment by dawid-g** [comment]
Issue is back on 9,7' i 4'7'.

**Comment by dawid-g** [comment]
ok, it's ok.
