### ISSUE TITLE
[Tablet] No possibility to select data range

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#62]
Preconditions: 
- IPAD Device 9,7'

1. Go to: /admin/users/index
2. Try to select data range

Results:

![range](https://user-images.githubusercontent.com/26220123/32939183-ffa67150-cb7e-11e7-9c4f-2337cb8cce0b.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been fixed.

**Comment by dawid-g** [comment]
verified as fixed.
