### ISSUE TITLE
[Tablet] Staff - Lack of Users submenu

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#67]
Preconditions:

- Ipad 9,7'

Steps:
1. Go to Configuration -> Staff

Results:
There is lack of Users submenu:
https://image.prntscr.com/image/MhsAwcXBTXa27pGNlpOchw.png

On short site menu it looks like this:
https://image.prntscr.com/image/8wYmAJEdTXCSLMZ80Oo6Vg.png

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
I have opened user submenu, and on the menu bar is "Groups": https://image.prntscr.com/image/6PKWwRPVSvO_H3CaEQaNlQ.png

There is no possibility, to back to "Groups" submenu.

**Comment by placidlyUnsalted** [comment]
@dawid-g That issue is fixed.

**Comment by dawid-g** [comment]
There is the same case for Short Top Menu template:

https://image.prntscr.com/image/-HcW_gobSuqToV6b7lEIZQ.png - lack of users submenu

**Comment by placidlyUnsalted** [comment]
@mountstone No side-menu when system on short top menu - why is that?

**Comment by mountstone** [comment]
@dawid-g Top menu has been added to short top meni scenario.

**Comment by dawid-g** [comment]
Can u show me where? 

https://image.prntscr.com/image/WhGK6O9xQp6p_ooUehJKSw.png

**Comment by mountstone** [comment]
@dawid-g fixed, please check it out

**Comment by dawid-g** [comment]
confirmed.
