### ISSUE TITLE
Notification Configuration - the number of days isn't displayed after submit

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#69]
1. Go to General Configuration -> System
2. Set random number of days in 'Remove notification logs every  days' field
3. Click submit 

Results:

After submit, and page refresh this field is empty.

**Comment by MarcinKozak** [comment]
@dawid-g @mountstone Not for me. @mountstone wrote it will handle with that.

**Comment by mountstone** [comment]
@dawid-g will be fixed in next release
