### ISSUE TITLE
[Tablet] Custom Fields - No possibility to enter fieldset

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#71]
Preconditions:
- Ipad 9,7'

Steps:

1. Go to Configuration -> Castom Fields -> Create custom Field
2. Try to enter some tekst to Fieldset field

Results: 

No possibility to enter tekst to Fieldset field.

![set](https://user-images.githubusercontent.com/26220123/32953766-81a72636-cbb1-11e7-8874-ec95b92ed53a.gif)

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
It's ok now. Closed.
