### ISSUE TITLE
Tools -> Import Translations - Clickability across the whole section area

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#72]
1. Go to Tools -> Translations -> Import (admin/translations/languages/import/en/admin)

Results:

- "Select csv file" on right upper corner 
- clickability across the whole section area

![import](https://user-images.githubusercontent.com/26220123/33011126-4385a232-cddd-11e7-8341-01881f262834.gif)

**Comment by mountstone** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
confirmed.
