### ISSUE TITLE
Import Translations - incorrectly data displaying

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#73]
Preconditions:
- Ipad 9,7'

1. Download this:  http://10.10.10.35:73/admin/translations/languages/export/en/admin
2. Go to /admin/translations/languages/import/en/admin 

There is first issue: https://image.prntscr.com/image/xScDXEuDQ6_O8ZS_UNYhEg.png  - to aligned

3. Import file

Second issue: https://image.prntscr.com/image/8Yps70itQJyE-P0Ymo3LnA.png - incorrectly data displaying

**Comment by placidlyUnsalted** [comment]
@mountstone need some layout adjustments.

**Comment by placidlyUnsalted** [comment]
@dawid-g After updates, these cases should be fixed now.

**Comment by dawid-g** [comment]
confirmed.
