### ISSUE TITLE
[Tablet] Very low issues

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#74]
Preconditions:
- Ipad 9,7'

- [x] 1. Go to admin/logger/information/index -> Run system analyzer
https://image.prntscr.com/image/1CsEjcxFRKKAvRHWkRoxhw.png

- [x] 2. CA - https://image.prntscr.com/image/K2bDzoASQL2phWlNyya28w.png

- [x] 3. /admin/acl/index/roles https://image.prntscr.com/image/dzO0gqdtQ9ujJCKFVvzWuw.png

**Comment by placidlyUnsalted** [comment]
@dawid-g After latest update, which includes template updates - issue has been delt with. :)

**Comment by dawid-g** [comment]
confirmed, but update

**Comment by placidlyUnsalted** [comment]
@dawid-g Third checkbox has also been taken care of. :)

**Comment by dawid-g** [comment]
verified as fixed.
