### ISSUE TITLE
[StandardView] Very low issues

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#75]
- [x] 1. /admin/tools/tester - "Test Connection" should be aligned
https://image.prntscr.com/image/z3l3IUiOQSureZnn9yeicw.png

- [x] 2. /admin/modules - Click install for random module, and look at "cancel" button colour
https://image.prntscr.com/image/Trhug9sPTaWARyUQ5nzKAg.png

- [ ] 3. /admin/tools/tester https://image.prntscr.com/image/6-0TE3MpSNqgDrq1aBRUvw.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Both issues fixed.

**Comment by dawid-g** [comment]
confirmed, but update

**Comment by dawid-g** [comment]
verified as fixed
