### ISSUE TITLE
[Smartphone] No possibility of user editing

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#78]
Precoditions:
- Smartphone 4,7'

1. Go to: /admin/users/index

Results: 
No possibility of user editing

![edycja](https://user-images.githubusercontent.com/26220123/33061270-ca7fb46c-ce9b-11e7-9961-e1612539cc8e.gif)

**Comment by dawid-g** [comment]
EDIT: 

Similar case in:  /admin/modules  on 5'


https://image.prntscr.com/image/TDuXUXr7SaSA6_0BUXy0tQ.png

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
https://image.prntscr.com/image/zeaOcspcSYGWdYWCuI4CAw.png - issue still occure, there is no possibility of entering the user editing page

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
verified as fixed.
