### ISSUE TITLE
[Smartphone] Very low issues

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#79]
Preconditions:
- smartphone 4,7'

- [x] 1.  admin/users/index:  https://image.prntscr.com/image/14VdJ1pyQsaJ4hF-S-x6Hw.png

- [x]  2. /admin/sample_module/index#  https://image.prntscr.com/image/PKNlJpxISsC367IyMIBuKQ.png

- [x] 3. /admin/customfields/user/index#  https://image.prntscr.com/image/ySE-x8K9Tdikok-C83MCWQ.png

- [x] 4. /admin/branding  https://image.prntscr.com/image/Ds5VuHxtR5GlDB9-oHTSQw.png

- [x] 5.  /admin/translations/index/admin   https://image.prntscr.com/image/2vJzvuV0Svu2YV-5HikFpA.png

- [x] 6. admin/logger/activity/index#  https://image.prntscr.com/image/EU2bJuh1S2KJ0QbsO9g9bA.png

- [x] 7. Forgot Password section https://image.prntscr.com/image/7yi-sUFeTWWJPYJEgDgrLQ.png

- [x] 8. Dashboard  https://image.prntscr.com/image/LyDuJ3APT-63LzGcPNH6ig.png

- [x] 9. admin/api/configuration  https://image.prntscr.com/image/0W3vtYgIQymbCBrOj7SkCA.png

- [x] 10. /admin/users/1 https://image.prntscr.com/image/AAo2_oVrQMazoFihgIjYtw.png

- [x] 11. /admin/translations/languages/import/en/admin  https://image.prntscr.com/image/RPc_GmFxRdOgcZ4AcbaOuQ.png

- [x] 12. /admin/translations/languages/import/en/admin  
 https://image.prntscr.com/image/z7aCHLHHS2_rhX4KBNjK9g.png

- [x] 13. https://image.prntscr.com/image/Gad_yu_9S5O-_-S_qk263A.png

- [x] 14. admin/translations/index/admin https://image.prntscr.com/image/OM0dqI2_QNqcb3diOLvU8Q.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Fixes to these issues were implemented recently.

**Comment by dawid-g** [comment]
update

**Comment by dawid-g** [comment]
update.

**Comment by dawid-g** [comment]
verified as fixed.
