### ISSUE TITLE
Not always visible Test Connection validation

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#80]
Preconditions: 
- smartphone 5'
- tablet 9,7'

Go to: /admin/settings/mail

Results:
Test connection validation is displayed at the bottom of the page and and if the user has a page set higher, it is not visible.

![tc](https://user-images.githubusercontent.com/26220123/33062956-33a3fcd2-cea1-11e7-9da2-35977de8a695.gif)

**Comment by placidlyUnsalted** [comment]
@mountstone Can we use standard system notification for this feature, instead of html alert?

**Comment by mountstone** [comment]
@tehaiks no

**Comment by dawid-g** [comment]
verified as fixed.
