### ISSUE TITLE
[Smartphone] Incorrect fields display

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#81]
Precoditions:
- Smartphone 4,7'

Go to: admin/customfields/1/edit

Results:
https://image.prntscr.com/image/l9N58bGQT4KVcI5jWk8rJQ.png

**Comment by placidlyUnsalted** [comment]
@mountstone Can you remove `w570` class from textarea?

**Comment by mountstone** [comment]
@tehaiks class removed

**Comment by placidlyUnsalted** [comment]
@mountstone Good job. 

@dawid-g Issue has been fixed. RWD layout is working correctly.

**Comment by dawid-g** [comment]
confirmed.
