### ISSUE TITLE
[Smartphone] Translations - incorrect data display

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#82]
Precoditions:
- Smartphone 4,7'

- [x] Go to: admin/translations/index/admin

Results:

![translations](https://user-images.githubusercontent.com/26220123/33070365-142885be-ceb8-11e7-989d-a4279f1719d6.gif)

- [x] Second thing -  don't know, why is there french flag all the time: https://image.prntscr.com/image/9eXBHjPEQ86uqBu3EejtfQ.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Yeah, you're right. Little CSS conflict as a result of brand styling. Should be allright now, though.

**Comment by dawid-g** [comment]
it's ok now, closed.
