### ISSUE TITLE
[Smartphone] Incorrect display of pagination

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#83]
Precoditions:
- Smartphone 4,7'

Go to: admin/translations/index/admin

Results:

https://image.prntscr.com/image/ndaiZgP4Rle7IF76RglJfA.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Pagination up-and-running on mobile. :)

**Comment by dawid-g** [comment]
confirmed :)
