### ISSUE TITLE
[Smartphone] Data after system analysis need to be aligned

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#84]
Precoditions:
- Smartphone 4,7'

1. Go to: admin/logger/information/index
2. Click Run System Analizer

Results:
![need](https://user-images.githubusercontent.com/26220123/33072324-5cf649fa-cebf-11e7-8913-a5292422b473.gif)

**Comment by mountstone** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
https://image.prntscr.com/image/pO9rLRQoSkaQxE9OBEeIvw.png  - there are still some small issue
