### ISSUE TITLE
[Smartphone] Account Details - Disappearing menu bar

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#85]
Precoditions:
- Smartphone 4,7'

1. Go to: /admin/account
2. Chose "Device" from menu bar on the top

Results:
The menu bar has disappeared - https://image.prntscr.com/image/hi9XLYhqSWqH19FWfo2oYw.png

**Comment by placidlyUnsalted** [comment]
@mountstone HTML on `/admin/logger/devices/index` lacks `.menu-mobile-settings--box` div.

**Comment by mountstone** [comment]
@tehaiks menu-mobile-settings--box added
@dawid-g please recheck

**Comment by dawid-g** [comment]
It's better, but when I have opened "Devices" submenu, on menu bar there is displayed "My Account". Should be "Devices".

https://image.prntscr.com/image/hCLlYgjwQPCv4iAVgqV9yA.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Taken to shop, reassembled and fixed.

**Comment by dawid-g** [comment]
verified as fixed.
