### ISSUE TITLE
[Smartphone] "Search" for particular sections don't response

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#86]
Preconditions:
- smartphone 4,7'

In the whole application there is a problem with the search engine for particular sections:

Sample:

![search](https://user-images.githubusercontent.com/26220123/33074871-fa3ad868-cec7-11e7-94a9-ed78c4e3bbb9.gif)

**Comment by mountstone** [comment]
@dawid-g fixed, but @drunkerbull should fix zero data effect for mobile view

**Comment by dawid-g** [comment]
confirmed.
