### ISSUE TITLE
[StandardView] Very low issues 

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#87]
- [x] 1. /admin/users/35 https://image.prntscr.com/image/R3dVAOrnSp2MY-V1rr2U3w.png
- [x] 2. CA  https://image.prntscr.com/image/PpD9vOgqR3_oRFkLNB-RYQ.png
- [x] 3. /admin/users/1 https://image.prntscr.com/image/AtkJsP_RRgiCxfRyJrqUXg.png - if name if widget i cute, there should be displayed full name during gover on it by the mouse pointer
- [x] 4. Login page https://image.prntscr.com/image/dDyvq4mcRqqVJ9PfsoE2SA.png -  login data stored in the browser
- [x] 5. /admin/settings/index  https://image.prntscr.com/image/iwBxeiCzSe2khwKrg5iwYQ.png

**Comment by placidlyUnsalted** [comment]
@mountstone Add `autocomplete="on"` to both inputs on login page.

**Comment by placidlyUnsalted** [comment]
@dawid-g 4th and 5th checkbox fixed. Can You kindly verify? :)

**Comment by dawid-g** [comment]
4, 5 verified as fixed.
