### ISSUE TITLE
[FullTopMenuView] Very low issues

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#88]
- [x] 1. https://image.prntscr.com/image/mZc6xC2sQMau4UvwRPc43A.png

- [x] 2. /admin/acl/index/users https://image.prntscr.com/image/ePPyJlMuR9SSmjEuYNbi2Q.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Both issues are fixed in latest version - can you verify?

**Comment by dawid-g** [comment]
1, 2 verified as fixed :)
