### ISSUE TITLE
[ShortTopMenu] Email Branding button - not necessary options display

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#89]
1. Enable ShortTopMenu
2. Go to admin/branding/area/1
3. Click on Email Branding button

Results:

https://image.prntscr.com/image/hF5tgYbtRM6C1fktZzVOHQ.png

**Comment by dawid-g** [comment]
Edit. There is the same case on on all other pages with similar buttons.

Sample: https://image.prntscr.com/image/qDS94xHsSceIq2Gd6wYsOw.png

**Comment by mountstone** [comment]
@dawid-g fixed
