### ISSUE TITLE
[ShortTopMenu] Lack of "Alerts" button

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#90]
ShortTopMenu

On the menu bar at the top of page, there should be "Alerts" button nex to "Notifications"

https://image.prntscr.com/image/k6SZOU2kS_eqZNwx0tQW4Q.png

**Comment by placidlyUnsalted** [comment]
@mountstone Should ShortMenuTemplate have alerts?

**Comment by mountstone** [comment]
@dawid-g @tehaiks nope, on ShortMenuTemplate we will use only notifications

**Comment by dawid-g** [comment]
Ok, closed.
