### ISSUE TITLE
[ShortTopMenu] Very low issues

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#91]
- [x] 1. Go to: admin/translations/index/admin, click on more: https://image.prntscr.com/image/D6ZAfLr7SHyoBOP4gkdwZg.png

- [x] 2. Dashboard https://image.prntscr.com/image/5XAadBudSmCBBodtXxz6PQ.png

- [x] 3. https://image.prntscr.com/image/neSjWJ4UTXmDPzsVmYieaQ.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Both issues are fixed in current version. Please verify.

**Comment by dawid-g** [comment]
update

**Comment by dawid-g** [comment]
verified as fixed.
