### ISSUE TITLE
[ShortTopMenu] Notification Templates - Should be button similar to those in this template

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#92]
1. Enable Short Top Menu
2. Go to /admin/notifications#

Results:
Should be button similar to those in this template
https://image.prntscr.com/image/SDrhd485QSCbC1KaKX5uMA.png

**Comment by mountstone** [comment]
@dawid-g Full top menu should have breadcrumb located on the left, in short top menu scenario breadcrumb should be located on the right

**Comment by dawid-g** [comment]
So if I have short top menu enabled:

https://image.prntscr.com/image/tosm0FKjSwiJmEBmjpmDKw.png

it should be breadcrumb located on the right?

**Comment by MarcinKozak** [comment]
@dawid-g  Awaiting for implementation instruction from @mountstone

**Comment by mountstone** [comment]
@dawid-g will be fixed in next release
