### ISSUE TITLE
[ShortTopMenu] Name of opened section unvisable on menu bar

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#97]
Go to: admin/settings/index

Results: 
Name of opened section unvisable on menu bar:
https://image.prntscr.com/image/2RafpB6BR2WelPC-ir-ZfA.png

**Comment by placidlyUnsalted** [comment]
@dawid-g This issue is fixed (active element). Can you kindly verify?

**Comment by dawid-g** [comment]
verified as fixed.
