### ISSUE TITLE
[ShortTopMenu] Unreadable menu

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#98]
https://image.prntscr.com/image/ky7aSQFTQL2d09gc6su4XQ.png   - In my opinion Menu bar on Short Top Menu template doesn't looks good, is unreadable. 

It's hard to say, Is that "Notification", "Templates" or "Notification templates".

**Comment by placidlyUnsalted** [comment]
@dawid-g Fixed!

**Comment by dawid-g** [comment]
verified as fixed.
